apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.fullname }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  type: LoadBalancer
  ports:
  {{- range $key, $value := .Values.nginx.ports }}
  - port: {{ $value }}
    name: {{ $key }}
  {{- end }}
  selector:
    app: {{ .Values.nginx.name }}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.nginx.fullname }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: mainflux-secret
      - name: configmap-volume
        configMap:
          name: {{ template "nginx.configMap.name" }}
      containers:
      - name: {{ .Values.nginx.fullname }}
        image: {{ .Values.nginxImage }}
        ports:
        {{- range $key, $value := .Values.nginx.ports }}
        - containerPort: {{ $value }}
        {{- end }}
        resources:
{{ toYaml .Values.defaultResources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/ssl/certs/mainflux-server.crt
          name: secret-volume
          subPath: mainflux-server.crt
        - mountPath: /etc/ssl/private/mainflux-server.key
          name: secret-volume
          subPath: mainflux-server.key
        - mountPath: /etc/ssl/certs/dhparam.pem
          name: secret-volume
          subPath: dhparam.pem
        - mountPath: /etc/nginx/nginx.conf
          name: configmap-volume
          subPath: nginx.conf
