apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nats.name }}
  labels:
    component: {{ .Values.nats.name }}
spec:
  selector:
    component: {{ .Values.nats.name }}
  clusterIP: None
  ports:
  ports:
  {{- range $key, $value := .Values.nats.ports }}
  - port: {{ $value }}
    name: {{ $key }}
  {{- end }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.nats.name }}
  labels:
    component: {{ .Values.nats.name }}
spec:
  serviceName: {{ .Values.nats.name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ .Values.nats.name }}
    spec:
      containers:
      - name: {{ .Values.nats.name }}
        image: {{ .Values.natsImage }}
        args: [ "--config", "/etc/nats/nats.conf"]
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats
        ports:
        {{- range $key, $value := .Values.nginx.ports }}
        - containerPort: {{ $value }}
          name: {{ $key }}
        {{- end }}
        resources:
{{ toYaml .Values.defaultResources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "nats.configMap.name" }}
