apiVersion: apps/v1beta1 
kind: Deployment 
metadata:
  name: {{ .Values.adapter.ws.name }}
  labels:
    component: {{ .Values.adapter.ws.name }} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ .Values.adapter.ws.name }}
    spec:
      containers:
      - name: mainflux-ws
        image: {{ .Values.wsAdapterImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8186
        env:
        {{- range $key, $value := .Values.adapter.ws.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
        resources:
{{ toYaml .Values.defaultResources | indent 10 }}
---
apiVersion: v1 
kind: Service 
metadata:
  name: {{ .Values.adapter.ws.name }}
  labels:
    component: {{ .Values.adapter.ws.name }} 
spec:
  selector:
    component: {{ .Values.adapter.ws.name }}
  ports:
  - port: 8186
  # type: LoadBalancer
